### ISSUE TITLE
WPy64-31101: ValueError: AST node line range (x,1) during runcell() in Spyder

### ISSUE THREAD

**Issue by Sven3141** [winpython/winpython#1186] opened 2023-01-06 16:06 UTC
Hi Everybody,

I've just switched from WPy64-31010 to WPy64-31101 and encountered the following problem:
Scripts containing string inputs for functions fail when running just a cell and not the entire py file or a single line.

This behavior showed first, when I tried to run just a cell changing labels and title of a matplotlib figure:
fig1.supxlabel('Time [s]')
fig1.supylabel('Angular Displacement [°]')
fig1.suptitle('Datapoint 0868')

I could reproduce this behavior in a "fresh" kernel session with the print() function:
![image](https://user-images.githubusercontent.com/122109044/211048554-0c9173b1-8269-4dda-b145-a07a06454e41.png)

In WPy64-31010 everything runs as expected.

Anybody encountered a similar behavior?

THX and cheers,
Sven

PS: Many thanks to the developers, I really appreciate the work you are doing, which saves me a lot of nerves and time to get the relevant tools in place and get the work done instead of working to get the tools working which get the work done :-)

**Comment by hiccup7** [comment] 2023-01-06 16:47
In this issue, the lead developer states that Spyder v5.4.2 will be released next week:
https://github.com/spyder-ide/spyder/issues/20302

Here are the problems that will be fixed (at a minimum) in v5.4.2:
https://github.com/spyder-ide/spyder/milestone/125

If your issue hasn't been reported yet (to be fixed in any milestone), the Spyder team is more likely to accept your report if you reproduce it in the Anaconda/Conda environment because the problem could be with the WinPython build.

@stonebig : Do you want to wait to release WinPython 2022-04 until Spyder v5.4.2 is available?

**Comment by stonebig** [comment] 2023-01-06 18:43
humm, running by clicking on 
![image](https://user-images.githubusercontent.com/4312421/211077824-826b6938-c664-4505-b527-bf191e1c7726.png) is ok

**Comment by stonebig** [comment] 2023-01-06 19:39
the issue I see in Spyder complains are:
- the dot completion https://github.com/spyder-ide/spyder/issues/20285
- Failed to render rich text help in Python 3.11:  https://github.com/spyder-ide/spyder/issues/20296

all other seems not for Windows, or because we kept an old version of pydocstyle.

**Comment by stonebig** [comment] 2023-01-06 19:47
investigating

**Comment by stonebig** [comment] 2023-01-06 20:02
on this issue, it seem also ok in master:
![image](https://user-images.githubusercontent.com/4312421/211090464-f4f0f119-4246-4afb-af00-92825b0f1b62.png)

**Comment by stonebig** [comment] 2023-01-06 20:10
only the https://github.com/spyder-ide/spyder/issues/20296 leaves me in doubts, as in theory the problem is still the in Python3.11, but I don't see it.... if someon can see it and then help spyder fix it ...

**Comment by stonebig** [comment] 2023-01-07 09:10
Maybe chatGPT can do the pre-job there ?

**Comment by stonebig** [comment] 2023-01-07 15:11
Hum..... 
![image](https://user-images.githubusercontent.com/4312421/211157519-2d37d553-ad53-4a23-ae7a-97414533f93f.png)

**Comment by stonebig** [comment] 2023-01-07 16:28
another guy had apparently the same idea as me, as he posted exactly the same solution.
... chatGPT is the new stackoverflow

**Comment by Sven3141** [comment] 2023-01-08 12:08
> @Sven3141 : Have you tried reproducing the problem in WinPython 3.10.9.0rc?

Hi guys,

thanks, I appreciate you effort. I have to admit, I cannot follow your replies 100% (I'm just the guy who is happy when everything works and who can focus on his analysis :-)), but I've testet my scripts as well as the "funny behavior" cell with  3.10.9.0rc and everything runs just fine. So, problem seems to be limited to 3.11.01.

Cheers,
Sven

**Comment by stonebig** [comment] 2023-01-08 12:12
if you try tihs in your editor, it shall not work well
![GIF_dot_completion_20230108](https://user-images.githubusercontent.com/4312421/211188586-740ab7f2-c9ff-4016-89bf-3feb5a264c4e.gif)

so there will be a rc2

**Comment by stonebig** [comment] 2023-01-08 12:16
Spyder project is under-staffed, gui testing in CI is complex, but I hope with new things like chatGPT or github Copilote [you] can help a lot

**Comment by stonebig** [comment] 2023-01-22 11:47
solved at rc2

**Closed by stonebig** 2023-01-22 11:47 UTC
