### ISSUE TITLE
Spyder crash

### ISSUE THREAD

**Issue by nzicher** [winpython/winpython#579] opened 2017-11-30 02:51 UTC
Hi,

I have tried using multiple versions of WinPython 64 bit including 3.6.3.0Qt5 and 3.5.4.1Qt5  
After successfully "installing" it, unpacking it, I don`t seem to ever be able to run Spyder. I have tried uninstalling the package and installing it manually but it doesn't work. It seems to start and prepare to load but just when "setting up main window" it crashes.
I am using Win 10
Can someone give me any tips on why this is the case?

Thank you very much.

**Comment by nzicher** [comment] 2017-11-30 03:29
Update:

After numerous trials, I have found a setup that allows me to launch Spyder.
It is WinPython 32bit 3.6.3.0Qt5 
I don't understand why this runs and the 64bit doesn't, considering my Win 10 is 64bit but I am happy that at least I managed to get it to start.
Now, on the other hand, I have another problem which says : 

Render Report Error
Can only launch a kernel on a local interface. Make sure that the '*_address' attributes are configured properly. Currently valid addresses are : ['192.168.1.2','0.0.0.0',"]

If anyone could help me with this I would greatly appreciate it.
Thanks

**Comment by stonebig** [comment] 2017-12-01 18:59
hum. what version of Windows10 ? 1703 (the creatore update ? 1709  (the this Fall Creator Update of 2 month ago) ?

**Comment by nzicher** [comment] 2017-12-04 11:25
Hey,
Sorry for the late reply. I have 1703. Will update to 1709 to see if that will help.

**Comment by stonebig** [comment] 2017-12-04 19:07
i have 1703 too, so i don't know what's the problem

**Comment by hiccup7** [comment] 2018-02-10 15:34
This issue seems to be a duplicate of https://github.com/winpython/winpython/issues/582 which was fixed by Spyder v3.2.6
@nzicher - Did upgrading to Spyder v3.2.6 or WinPython-64bit-3.6.4.0Qt5b4 (or later) solve your issue?

**Comment by nzicher** [comment] 2018-02-10 23:29
@hiccup7 Sorry, but I actually didn't use WinPython for over a month now (I was just using WinPython 32bit 3.6.3.0Qt5 while the issue persisted). I am currently working on a Mac so I am unable to offer any information on that. Thanks to everyone who worked on this and got it fixed.

**Comment by hiccup7** [comment] 2018-02-11 13:13
@nzicher No need for you to do further testing with Spyder on WinPython if you are not using it.  Please close this issue.  There are a number of duplicates of #582 still open, and they give people the wrong impression about compatibility of WinPython and Spyder.

**Closed** 2018-02-11 13:39 UTC
