### ISSUE TITLE
vs2015 python 3.5

### ISSUE THREAD

**Issue by sbant** [winpython/winpython#67] opened 2015-03-20 08:16 UTC
https://www.python.org/downloads/release/python-350a1/

The Windows binaries were built with Microsoft Visual Studio 2015, which is not yet officially released. (It's currently offered in "Preview" mode, which is akin to a "beta".) It is our intention to ship Python 3.5 using VS2015, although right now VS2015's final release date is unclear.

Python 3.5.0 alpha 3 will released at Release date: 2015-03-28

now, there are too many different visual studio versions on pc, since python 3.5 will use vs2015,is that
any plan to test build winpython with vs2015?
then we can use single version VS..

**Comment by stonebig** [comment] 2015-03-20 17:10
I only use the same mingw32/64-static-2014-11  version for all python versions.
==> I guess it should work with Python3.5 too.

That is possible because mingw-static creates static dlls.
Any other solution (than static dll) is a pain for a multi-python Windows distribution, as you notice.

see https://github.com/numpy/numpy/wiki/Mingw-static-toolchain

**Comment by carlkl** [comment] 2015-04-23 13:47
python-3.5 / VS2015 is not yet supported by mingwpy (mingw-static-toolchain), This may change for the future.

**Comment by stonebig** [comment] 2015-04-23 14:39
Is it about C99 support ? Having to move to GCC 5.2 ?

**Comment by carlkl** [comment] 2015-04-23 16:46
It is about msv runtime support. mingw-w64 supports msvcrt and msvcr80,90,100,110. VS2015 has a new concept of runtimes http://blogs.msdn.com/b/vcblog/archive/2014/06/10/the-great-crt-refactoring.aspx?PageIndex=2  that as to be included by the mingw-w64 community first.

**Comment by stonebig** [comment] 2015-04-23 17:36
I don't find a hint of this move on mingw-w64 community, but I don't really know what keyword to look for.

Is there some movement on this ? 

Do you have a sort of interval of confidence of when this happy event may happen ? 

[2015-july .. 2015-december] ?

**Comment by carlkl** [comment] 2015-04-23 18:34
No, and I don't have an idea when VS2015 will be released officially ;)
However, I know from private contact, that the mingw-w64 community is aware of the problem.

**Comment by stonebig** [comment] 2015-04-25 07:11
My revised interval of confidence is now stretching very far on the right.

http://stevedower.id.au/blog/the-python-3-5-installer/#comment-241

**Comment by ogrisel** [comment] 2015-04-27 09:26
@sbant using only vs2015 to build the full WinPython distrib is not possible as some packages such as scipy need a fortran compiler which Microsoft does not support but mingw-w64 does.

**Comment by stonebig** [comment] 2015-04-27 16:49
in my dream, Python 3.5 goes back to Visual Studio 2013.

**Comment by carlkl** [comment] 2015-04-30 09:38
I'm aware of "The Great C Runtime (CRT) Refactoring", see http://blogs.msdn.com/b/vcblog/archive/2014/06/10/the-great-crt-refactoring.aspx?PageIndex=2. This includes long awaited C99 support for the MSVC compilers. It is on the other hand a complete redesign of the C-runtime handling.
Future will show, when and how this will be supoorted by the mingw-w64 community.

**Comment by stonebig** [comment] 2015-04-30 16:34
no doubts it's an improvement, and a move towards standards.
Just I'm looking for a compiler toolchain shippable in Winpython-3.5.0 this september 2015.

**Comment by stonebig** [comment] 2015-05-03 05:28
reading this http://www.riverbankcomputing.com/pipermail/pyqt/2015-March/035633.html

Chromium is not embedded in PyQt5.4 for Windows because `it needs a later compiler than the one used for Python v3.`

**Comment by carlkl** [comment] 2015-05-19 11:03
The VS2015 concept of relying on an universal CRT as described in http://blogs.msdn.com/b/vcblog/archive/2015/03/03/introducing-the-universal-crt.aspx  will have a consequence for Winpython as a fully portable distribution - *if used with Python-3.5*. The now necessary universal CRT **ucrtbase.dll** has to be installed with admin privileges on Windows boxes <= 8.1. It *may* come with windows updates automatically, but this cannot not be garantueed. Only Windows10 incudes this CRT by default.

**Comment by stonebig** [comment] 2015-05-19 17:20
it can't be shipped at the usual `WinPython-32bit-3.5.0.1\python-3.5.0\` place ?

**Comment by carlkl** [comment] 2015-05-19 18:40
this is hopefully going to be changed in foreseeable future, as unversal CRT now seems to be the new Windows standard CRT. See http://article.gmane.org/gmane.comp.gnu.mingw.w64.general/11368 and http://article.gmane.org/gmane.comp.gnu.mingw.w64.general/11374. 
Another aspect is, that universal CRT is going to be installed as Windows update to Windows7/8 in near future. You can however not be sure that every Windows box is automatically updated, so WinPython-3.5 will have a dependancy on Windows10 OR Windows7,8 with updates.
HINT: ucrtbase.dll has to be installed into the Windows system librarie folder and can't be installed side by side with Python.

**Comment by stonebig** [comment] 2015-05-21 20:32
I see more hope in the mission statement here: http://bugs.python.org/issue4709#msg243630

`I'd like to see a single-file "download, unzip, and use" distribution rather than the current rather intimidating set of instructions on how to set the toolchain up`

That sounds "Voice of the Customer".

**Comment by stonebig** [comment] 2015-06-09 19:45
"Voice of the Packager": http://bugs.python.org/issue24385

**Comment by stonebig** [comment] 2015-06-09 20:19
It seems necessary concessions have been made so Mercurial and Twisted projects can fully migrate to Python3.5

https://mail.python.org/pipermail/python-dev/2015-May/140407.html

**Comment by carlkl** [comment] 2015-06-09 20:34
I can try out configuring a toolchain based on the new universal runtime for testing. The C99 stuff will be augumented in this case with mingw-w64 own implementations. I have no clue if this will yield a working solution though.

**Comment by stonebig** [comment] 2015-06-09 21:00
If Steve has some connexions into the Microsoft side, every problem mingw experts will report **should** get an active help from Microsoft, and so it would be a waste not to try them now.

Maybe I'm wrong.

**Comment by carlkl** [comment] 2015-06-10 08:13
I can try out configuring a toolchain based on the new universal runtime for testing. The C99 stuff will be augumented in this case with mingw-w64 own implementations. I have no clue if this will yield a working solution though.

**Comment by carlkl** [comment] 2015-06-10 08:16
according to https://bugs.python.org/issue23970 Python-3.5 for Windows will be built with MS Visual Studio 14 instead. This is a complete different ecosystem.

**Comment by stonebig** [comment] 2015-06-10 17:26
I will wait to get the vs2015 "runtime" via windows update, before trying my first initial Winpython3.4
I don't know when it will be pushed down on Windows7.

**Comment by stonebig** [comment] 2015-06-30 17:30
hi @carlkl , do you see some progress on this ? Maybe vs 2015 being still in RC means no progress possible ?

**Comment by carlkl** [comment] 2015-07-01 07:47
I didn't proceed much with the universal crt stuff. ucrtbase.dll seems to be a moving target right now, so it's better to wait for the advent of Python-3.5rc1.

**Comment by stonebig** [comment] 2015-07-19 10:41
apparently vs2015 final arrives July 20th, and so Python3.5 beta4 of July 26th will use hopefully the first stable ucrtbase.dll

**Comment by stonebig** [comment] 2015-07-21 18:31
hi Carl,

Is it  you also here https://anaconda.org/carlkl/Cython/files ?

What about the mingwpy 1.0b1 , compared to the April 17th version of https://bitbucket.org/carlkl/mingw-w64-for-python/downloads ?

**Comment by carlkl** [comment] 2015-07-21 20:05
Hi @stonebig,

yes it is me. mingwpy 1.0b1 is the first attempt to deploy an easy to install compiler toolchain, that only needs ```pip install mingwpy``` and ```<pythonroot>\Scripts``` to be in the PATH. However, this versions showed up to be buggy on some computers (access denied errors). A new version is planned for the weekend.

You can try it out with winpython. You have to remove the PATH to ```tools\mingw32\bin```, because this path is favoured due to the sequence you defined in your batch files.

**Comment by stonebig** [comment] 2015-07-21 21:40
I"ll happily trade some lines od DOS scripts for a standard pip installation.

Will I need to install the `Libpython` of Christoph Gohlke with mingwpy of this week-end ?

**Comment by carlkl** [comment] 2015-07-22 07:46
No,
mingwpy comes with it's own libpython - and will overwrite an existings one.

**Comment by stonebig** [comment] 2015-07-27 15:44
python 3.5b4 was released yesterday.
Christoph Gohlke released his first 3.5 wheels today.

Time to start experiments.

**Comment by stonebig** [comment] 2015-07-27 17:11
KB2999226 installs the c runtime library... users will have to install it by themselves, let's hope it will come in windows automatic update.

**Comment by stonebig** [comment] 2015-07-27 17:57
so sad to see this:
````python
D:\WinPython\basedir35\build\winpython-3.5.0.amd64\scripts>python
Python 3.5.0b4 (v3.5.0b4:c0d641054635, Jul 26 2015, 07:11:12) [MSC v.1900 64 bit
 (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3;sqlite3.sqlite_version
'3.8.3.1'
>>>
````

**Comment by stonebig** [comment] 2015-07-27 17:59
please ship a recent sqlite, or don't ship any. this one is buggy

**Comment by stonebig** [comment] 2015-07-27 21:50
@carlkl with mingwpy 0.1.0b3:
- should we be more stable than previous version ?
- what official adress to put ? https://anaconda.org/carlkl/mingwpy ?
- It seems to work as usual, but I suppose you removed blas/lapack as it looks smaller ?

**Comment by stonebig** [comment] 2015-07-28 13:53
trying to start ipython notebook, it aks me VCRUNTIME140.dll

**Comment by carlkl** [comment] 2015-07-28 16:21
mingwpy-0.1.0b3 should be stable. The previous version showed access denied errors for the launcher binaries in Scripts in some cases. 
More libraries, i.e. OpenBLAS will come as seperate subpackages.

**Comment by stonebig** [comment] 2015-07-28 17:27
ok, thank you. I do the change

**Comment by stonebig** [comment] 2015-07-29 05:52
shouldn't you register names on pypi ?

**Comment by carlkl** [comment] 2015-07-29 17:44
@stonebig, please give me feedback if you encounter problems with this version of mingwpy. I will make an announcement on PYPI ASAP. First of all I have to deploy documentation and patches on https://github.com/mingwpy. This is mandantory, not only for legal reasons (FSF) but also to allow the community to participate.

**Comment by stonebig** [comment] 2015-07-29 17:52
so far no issue, but I only tried Winpython_checker stupid test.
==> I'll upload a build very soon, so others can experiment.

My main issue is that no having "openblas" may be a blocker for Theano users, but I'm not certain of this.

**Comment by carlkl** [comment] 2015-07-29 18:04
AFAIK theano indirectly uses scipy's BLAS in the default configuration.

2015-07-29 19:52 GMT+02:00 stonebig <notifications@github.com>:

**Comment by stonebig** [comment] 2015-07-29 18:53
ok, pushed on https://github.com/winpython/winpython/releases/tag/1.2.20150729

**Comment by carlkl** [comment] 2015-07-29 20:38
@stonebig, please give me feedback if you encounter problems with this version of mingwpy. I will make an announcement on PYPI ASAP. First of all I have to deploy documentation and patches on https://github.com/mingwpy. This is mandantory, not only for legal reasons (FSF) but also to allow the community to participate.

**Comment by stonebig** [comment] 2015-07-29 21:41
oups! I dropped this cygnwincompiler patch when simplifying too much
````
if not  %WINPYARCH%=="WIN-AMD64" goto no_distutil_patch
%~dp0Find_And_replace.vbs "%WINPYDIR%\Lib\distutils\cygwinccompiler.py" "-O -W" "-O -DMS_WIN64 -W"
:no_distutil_patch
````

I shouldn't have.

**Comment by carlkl** [comment] 2015-07-30 05:19
-DMS_WIN64 is set from within the gcc specs (mingwpy toolchain 64 bit only), so this patch is not needed anymore.

**Comment by stonebig** [comment] 2015-07-30 15:50
ok.

**Comment by stonebig** [comment] 2015-08-01 07:11
@carlkl it seems I have an issue, but not ultra-certain. I get a waring mesage on winpython-checker over theano test:
````
# Checking Theano

import theano.tensor as T

from theano import function

x = T.dmatrix('x')

y = T.dmatrix('y')

z = x + y

f = function([x, y], z)

f([[1, 2], [3, 4]], [[10, 20], [30, 40]])

WARNING (theano.gof.compilelock): Overriding existing lock by dead process '4552' (I am process '5812')
WARNING:theano.gof.compilelock:Overriding existing lock by dead process '4552' (I am process '5812')
````

**Comment by stonebig** [comment] 2015-08-01 13:16
problem disappeared when I try to reproduce... strange.

**Comment by carlkl** [comment] 2015-08-01 18:08
```Overriding existing lock by dead process``` is a theano issue, i.e. https://github.com/Theano/Theano/issues/1319

**Comment by stonebig** [comment] 2015-08-01 18:42
ok. I'm heading for a release end of next week with 'mingwpy' as special feature.
(openblas wheel or not)

**Comment by stonebig** [comment] 2015-08-23 21:44
hi  @carlkl , hope you're well. 

Do you have any suggestion on how to best detect the compiler ? https://github.com/PierreRaybaut/guiqwt/issues/1#issuecomment-133913906

**Comment by carlkl** [comment] 2015-08-24 08:45
@stonebig, could you try the following code snippet

```python
# mingw32 compiler configured in %USERPROFILE%\pydistutils.cfg 
# or distutils\distutils.cfg
from distutils.dist import Distribution
_dist = Distribution()
_dist.parse_config_files()
_bld = _dist.get_option_dict('build')
if _bld and 'mingw32' in _bld.get('compiler'):
    return True
```
you can check for ```build_ext``` instead of ```build``` as well

**Comment by stonebig** [comment] 2015-08-24 09:20
Thanks !

**Comment by stonebig** [comment] 2015-08-26 06:42
Interesting reading.
http://stevedower.id.au/blog/building-for-python-3-5/

**Comment by carlkl** [comment] 2015-08-31 14:12
newer binary wheels for numpy-1.9.2 and scipy-0.16.0 (mingwpy/OpenBLAS flavour) are now available at https://anaconda.org/mingwpy. pip install of the the packages works as follows:

```bash
pip install -i https://pypi.anaconda.org/mingwpy/simple numpy
pip install -i https://pypi.anaconda.org/mingwpy/simple scipy
```
New mingwpy wheels will follow soon.  Preparing for Python-3.5 is still not available will take some time.

**Comment by stonebig** [comment] 2015-08-31 16:32
Hi @carlkl,

Thanks for the update. I wIll take new mingwpy wheels.

**Comment by stonebig** [comment] 2015-09-01 16:50
Will  there be a changelog with the  mingwpy wheels ?

**Comment by carlkl** [comment] 2015-09-01 17:47
all information will be deployed on https://github.com/mingwpy. It's just a matter of available free time.

**Comment by stonebig** [comment] 2015-09-02 17:56
a "free" MKL ? https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/kLnwL1cqMcE

**Comment by carlkl** [comment] 2015-09-04 15:41
The community MKL needs registration at Intel and works together with MSVC. If parts of it are usuable via dynamic linking with mingwpy is unclear. 
However, the license sitation of numpy+MKL is much improved with this community MKL  as far I can see (I'm not at lawyer)

**Comment by stonebig** [comment] 2015-09-05 11:04
I see that llvm 3.7.0 has now windows binaries.. Could it be a possible portable/usb compiler solution at least for the cython part of python 3.5 ?

**Comment by carlkl** [comment] 2015-09-05 11:38
The official Windows LLVM binaries depend on an installed Visual Studio, or did I miss something new?

**Comment by stonebig** [comment] 2015-09-05 12:10
ah, it's never clear to me what there is in llvm. maybe should I mean Clang for windows ?

**Comment by carlkl** [comment] 2015-09-05 14:25
LLVM / clang may work together with mingwpy (mingw-w64) as well, I'm not sure. However, you need a full featured compiler toolchain in addition to the LLVM binaries you mentioned. clang is simply a part of LLVM. 
AFAIK LLVW on Windows lacks linker, libraries and import libraries to build binaries, so it is more an addon to an existing compiler than a complete solution.

**Comment by carlkl** [comment] 2015-09-09 14:07
seeing http://bugs.python.org/issue25027 I propose to wait for a solution until digging more into mingwpy / VS 2015 crt runtime compatibility.

**Comment by stonebig** [comment] 2015-09-09 16:28
sure. Thanks for the link, Carl.

**Comment by stonebig** [comment] 2015-11-06 18:27
checklist of missing wheels for Python 3.5:
- [ ] mingwpy 
- [ ] Pulp 
- [ ] PyQt5 
- [ ] pywin32
- [ ] rpy2

**Comment by carlkl** [comment] 2015-11-06 19:16
at least pywin32 for python-3.5 is available from http://sourceforge.net/projects/pywin32/files/pywin32/Build%20219

**Comment by stonebig** [comment] 2015-11-06 19:48
ah yes, there is this solution, if no wheels turn up

**Comment by cgohlke** [comment] 2015-11-07 02:04
FWIW, those pywin32 binaries were built with Visual Studio 2010 against a "prehistoric" version of Python 3.5. Pywin32 does not currently compile with Visual Studio 2015 against Python 3.5 final.
Pulp/CoinMP binaries for Python 3.5 were not stable last time I tried (August).
rpy2 waits for mingwpy, although Rtools could do instead.

**Comment by carlkl** [comment] 2015-11-07 08:09
mingwpy for python-3.5 will be available as soon as correct CRT runtime linkage is supported (ucrt: universal runtimes). This is not the case for RTools, they link against msvcrt AFAIK. 

The problem with runtime mixing is the following: it may work for one project, but not for another. And problems may raise unexpectedly at runtime during usage.

I didn't take a look at rpy2: RTools may work here.

Another solution one may to try out as package builder is to install CLANG into VS2015 and use clang-cl.exe instead of cl.exe.

**Comment by cgohlke** [comment] 2015-11-07 09:42
rpy2 binaries for Python 3.5 are now available. Replaced pywin32 with winreg and ctypes.

**Comment by stonebig** [comment] 2015-11-08 21:52
@cgohlke,

I just notice:
- numpy‑1.9.3+mkl‑cp34‑none‑win_amd64.whl = 116 Mo
- numpy‑1.9.3+mkl‑cp35‑none‑win_amd64.whl = 27 Mo

Is it normal ?

**Comment by carlkl** [comment] 2015-11-09 15:03
I guess it is due to the fact that with VS2015 a compatible INTEL-MKL is now free distributable and allows dynamic linking of the MKL DLLs. This adds a lot of MKL stuff to numpy but saves a lot of space for scipy builds based on numpy-MKL.

**Comment by stonebig** [comment] 2015-11-09 19:27
Thanks for your answer. I didn't know the licence change was not applying for VS 2010 versions

**Comment by stonebig** [comment] 2015-11-09 21:46
Without pywin32, I fail to build WinpythonSlim on Python 3.4: it blows up on a simple post-install dos step:
````
echo =================
echo finish install seaborn iris example
echo =================
if exist  "%WINPYDIR%\Lib\site-packages\seaborn" %WINPYDIR%\python.exe -c "import seaborn as sns;sns.set();sns.load_dataset('iris')"
````

**Comment by stonebig** [comment] 2015-11-10 08:18
Apparently, this basic example of seaborn doesn't work without pywin32:
````
import seaborn as sns
sns.set()
plt.plot(x, np.sin(x), x, np.cos(x));
````

````
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-08d3ed297dbe> in <module>()
----> 1 import seaborn as sns
      2 sns.set()
      3 plt.plot(x, np.sin(x), x, np.cos(x));

D:\WinPython\basedir34\buildSlim\winpython-3.4.3\python-3.4.3\lib\site-packages\seaborn\__init__.py in <module>()
----> 1 from .rcmod import *
      2 from .utils import *
      3 from .palettes import *
      4 from .linearmodels import *
      5 from .categorical import *

D:\WinPython\basedir34\buildSlim\winpython-3.4.3\python-3.4.3\lib\site-packages\seaborn\rcmod.py in <module>()
      5 import matplotlib as mpl
      6 
----> 7 from . import palettes
      8 
      9 mpl_ge_150 = LooseVersion(mpl.__version__) >= '1.5.0'

D:\WinPython\basedir34\buildSlim\winpython-3.4.3\python-3.4.3\lib\site-packages\seaborn\palettes.py in <module>()
     10 from .external.six.moves import range
     11 
---> 12 from .utils import desaturate, set_hls_values, get_color_cycle
     13 from .xkcd_rgb import xkcd_rgb
     14 from .crayons import crayons

D:\WinPython\basedir34\buildSlim\winpython-3.4.3\python-3.4.3\lib\site-packages\seaborn\utils.py in <module>()
      6 
      7 import numpy as np
----> 8 from scipy import stats
      9 import pandas as pd
     10 import matplotlib as mpl

D:\WinPython\basedir34\buildSlim\winpython-3.4.3\python-3.4.3\lib\site-packages\scipy\stats\__init__.py in <module>()
    319 from __future__ import division, print_function, absolute_import
    320 
--> 321 from .stats import *
    322 from .distributions import *
    323 from .morestats import *

D:\WinPython\basedir34\buildSlim\winpython-3.4.3\python-3.4.3\lib\site-packages\scipy\stats\stats.py in <module>()
    178 from scipy._lib.six import callable, string_types
    179 from numpy import array, asarray, ma, zeros
--> 180 import scipy.special as special
    181 import scipy.linalg as linalg
    182 import numpy as np

D:\WinPython\basedir34\buildSlim\winpython-3.4.3\python-3.4.3\lib\site-packages\scipy\special\__init__.py in <module>()
    599 from __future__ import division, print_function, absolute_import
    600 
--> 601 from ._ufuncs import *
    602 
    603 from .basic import *

ImportError: DLL load failed: Le module spécifié est introuvable.
````

**Comment by cgohlke** [comment] 2015-11-10 22:01
Scipy requires numpy+MKL.
To save space, for Python 3.5, you could try to remove several DLLs from `numpy/core`, e.g. `*avx*.dll` and `*mc*.dll`.
carlkl's explanation about the binary sizes is correct. Besides that, statically linking to MKL 11.3 created huge binaries. Distributing the MKL DLLs with numpy is significantly smaller overall. 
I have not yet switched to MKL 11.3 for Visual Studio 2010 builds.

**Comment by stonebig** [comment] 2015-11-10 22:27
ok

**Comment by stonebig** [comment] 2015-11-11 18:21
Hi @carlkl,

I need advice on this.
 
I try to create a first winpython 3.5 'Slim' (so no mingwpy), i use this receipe:
- execute once a Python3.5 install 
- zip the `python-3.5.0.amd64` directory result for direct unziop in next build process
- doing that I get all as usual, but:
   - for Python 3.4 I was copying `msvcr100.dll` and `msvcp100.dll` next to python.exe (https://github.com/winpython/winpython/blob/master/winpython/disthelpers.py#L127)
   - what shall I do for Python 3.5 instead (If I have to do anything) ?

**Comment by stonebig** [comment] 2015-11-11 18:49
first try:
- IDLE works !
- jupyter-notebook fails on this:
````
D:\WinPython\basedir35\build\winpython-3.5.0.amd64\python-3.5.0.amd64>jupyter-no
tebook
Traceback (most recent call last):
  File "D:\WinPython\basedir35\build\winpython-3.5.0.amd64\python-3.5.0.amd64\li
b\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\WinPython\basedir35\build\winpython-3.5.0.amd64\python-3.5.0.amd64\li
b\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\WinPython\basedir35\build\winpython-3.5.0.amd64\python-3.5.0.amd64\Sc
ripts\jupyter-notebook.exe\__main__.py", line 5, in <module>
  File "D:\WinPython\basedir35\build\winpython-3.5.0.amd64\python-3.5.0.amd64\li
b\site-packages\notebook\notebookapp.py", line 32, in <module>
    from zmq.eventloop import ioloop
  File "D:\WinPython\basedir35\build\winpython-3.5.0.amd64\python-3.5.0.amd64\li
b\site-packages\zmq\__init__.py", line 47, in <module>
    _libzmq = ctypes.cdll.LoadLibrary(bundled[0])
  File "D:\WinPython\basedir35\build\winpython-3.5.0.amd64\python-3.5.0.amd64\li
b\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "D:\WinPython\basedir35\build\winpython-3.5.0.amd64\python-3.5.0.amd64\li
b\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Le module spécifié est introuvable

D:\WinPython\basedir35\build\winpython-3.5.0.amd64\python-3.5.0.amd64>
````

**Comment by stonebig** [comment] 2015-11-11 19:30
I apparently MSVCP140.dll

**Comment by cgohlke** [comment] 2015-11-11 19:45
For Python 3.5, you should include the following DLLs, which are required in addition to the UCRT:

* vcruntime140.dll
* msvcp140.dll
* vccorlib140.dll
* concrt140.dll
* vcomp140.dll

**Comment by stonebig** [comment] 2015-11-11 19:45
but where are they on my PC ?

**Comment by stonebig** [comment] 2015-11-11 20:31
a WinPython3.5.0.0Slim worksnow on my pc

**Comment by stonebig** [comment] 2015-11-11 22:03
a WinPython3.5.0.1Slim is uploaded to sourceforge.

**Comment by stonebig** [comment] 2015-11-12 22:03
so, it works out-of-the-box as expected on Windows 10 PCs,

Short term issues:
- wait (december+) PyQt 5.6.0 to have a PyQt5 instead of a PyQt4,

Longer term issues:
- no theano/pymc3/lasagne/Keras in sight until mingwpy becomes compatible.
- no clear node.js (node-gyp) solution yet.

**Comment by carlkl** [comment] 2015-11-23 09:31
another catch:

a portable python-3.5 should contain a file called ```pyvenv.cfg``` with the following line:

```applocal = true```

see https://bugs.python.org/issue23955 and the document ```Python Setup and Usage```:

```
If a pyvenv.cfg file is found alongside the main executable or in the directory one level 
above the executable, the following variations apply:
- If home is an absolute path and PYTHONHOME is not set, this path is used instead of 
  the path to the main executable when deducing the home location.
- If applocal is set to true, the home property or the main executable is always used as 
  the home path, and all environment variables or registry values affecting the path are 
  ignored. The landmark file is not checked.
```

**Comment by stonebig** [comment] 2015-11-23 17:19
ok, I'll put it next to the python.exe

**Comment by carlkl** [comment] 2015-11-24 22:32
And another one found on http://sourceforge.net/p/msys2/wiki/Launchers 

http://sourceforge.net/p/msys2/mailman/message/34599465

**Comment by stonebig** [comment] 2015-11-25 17:10
Hi @carlkl ,

What do you mean ? we don't ship msys2, as far as I know, do we ?

**Comment by carlkl** [comment] 2015-11-25 19:58
@stonebig, I havn't tested it. On a first look it seems like a nice exe-launcher, that allows easy customization of environment variables before start per ini-file. Maybe an alternative for bat-files?

**Comment by stonebig** [comment] 2015-11-25 20:09
ah, ok. I was focussing on the "mys2" part of the link.

**Comment by carlkl** [comment] 2015-11-25 20:47
there is also ```bat_to_exe```  http://www.f2ko.de/de/b2e.php to consider.

**Comment by stonebig** [comment] 2015-11-25 21:03
Lookign for new, I read somewhere thar mingwpy for Python 3.5 needs 3 man-month of paid work, so not anywhere close at the moment. Is it that bad ?

**Comment by carlkl** [comment] 2015-11-26 08:21
There is a broad scope of work to do in the context of VS compatibility, mingwpy, scipy-stack and openblas. There is no decision reached on the organisation of work AFAIK. Write me an email if you like to participate yourself in the discussions.

**Comment by dead** [comment] 2015-12-17 02:27
Is Theano working in python 3.5?
I'm getting "ImportError: DLL load failed"

**Comment by stonebig** [comment] 2015-12-17 05:50
As far as I know, there is currently no compatible compiler for both Theano and Python 3.5.

Mingwpy/mingw-64, that we use happily for 3.4, needs "sponsors" to become Python3.5-on-windows compatible.

I didn't hear about a viable alternative to mingwpy (let me know if you see one), so we have to wait.

**Comment by carlkl** [comment] 2015-12-19 16:40
there is now https://mingwpy.github.io for news and further discussions about mingwpy

**Comment by stonebig** [comment] 2015-12-19 18:30
Super ! 

At the moment issues are listed in the Wiki. Would  it make sense to open them as small separated github "issues" ?  on https://github.com/mingwpy/mingwpy.github.io/issues ?

**Comment by carlkl** [comment] 2015-12-19 19:26
Just feel free to open issues / PR's

**Comment by stonebig** [comment] 2015-12-25 14:04
Pulp 1.6.1 is available for Python 1.5.9, just now twice the binary wheel size.
![pulp](https://cloud.githubusercontent.com/assets/4312421/12003298/baa0d6f0-ab18-11e5-8c16-9623ccd3f39e.GIF)

**Comment by stonebig** [comment] 2016-01-17 16:26
Mingwpy effort has just received some support:
https://github.com/rgommers/mingwpy.github.io/commit/4bb95ba09267d8000ea0a0a85a48318893fc629c

**Comment by stonebig** [comment] 2016-02-06 11:58
I suppose we may see significative progress this spring

**Comment by stonebig** [comment] 2016-02-14 16:43
Wouldn't an intermediate refresh of mingwpy, to 1.0.0b4 with a refreshed gcc 5.3.3 make sense ?

**Comment by carlkl** [comment] 2016-02-14 20:26
Yes, but python-3.5 will not be supported right now.

**Comment by stonebig** [comment] 2016-02-14 20:54
That was not my expectation. Still, puting a release on Pypi may bring some publicity and added resource to mingwpy.

**Comment by stonebig** [comment] 2016-03-20 18:44
Apparently, latest pymc3 and Theano can survive with older mingwpy-0.1.0b3, on Python3.4

**Comment by carlkl** [comment] 2016-03-20 20:16
Info: around next week there will be the next version of mingwpy ready. Based on gcc-5.3.0 but no python-3.5 support so far.

**Comment by stonebig** [comment] 2016-03-20 20:51
Hi @carlkl,

That wiil be great, thanks !

**Comment by carlkl** [comment] 2016-03-28 21:18
This is a RFC: mingwpy for python-3.5 *could* be provided with a significant limitation: 
**no support for the universal runtime UCRT but using msvcrt instead**

This may be enough to support of theano, pymc3 and simple cython extensions but will fail with memory allocation/deallocation and file streams usage across DLL boundaries. So this should be documented carefully for the uninitiated. A segfault is only one step away with such a configuration.

On the other hand this may be helpful to find other sources of bugs with the usage of mingwpy and python-3.5.

**Comment by stonebig** [comment] 2016-03-29 17:14
I'm 200% for that intermediate move:
- the first step is enough for me to get usable benefits,
- several intermediate steps may help you get more sponsors and direct help.

**Comment by stonebig** [comment] 2016-04-29 17:51
any hint of a date for next mingwpy official wheel ?

**Comment by stonebig** [comment] 2016-05-28 11:38
any guess of an approximative date for next mingwpy official wheel ?

**Comment by carlkl** [comment] 2016-06-06 21:34
I will deploy new wheels next week. However, the VS2015 variant _without_ VS2015 runtime DLL support will not be named **mingwpy** to avoid confusion of the users.

**Comment by stonebig** [comment] 2016-06-07 17:52
that's great news. Will I need to change "pydistutils.cfg" because of the name change ?
````
[config]
compiler=mingw32
[build]
compiler=mingw32
[build_ext]
compiler=mingw32
````

**Comment by carlkl** [comment] 2016-06-09 15:40
**mingw32** is the valid keyword for _all_ variants of mingw32 and mingw-w64 including mingwpy.

**Comment by stonebig** [comment] 2016-06-19 09:35
Alles mingwpy Gescheite ist schon gedacht worden, man muß nur versuchen, es noch einmal hochladen zu denken.

**Comment by stonebig** [comment] 2016-07-20 18:13
the guy who spoke of the imminent Matplotlib 2.0 last scipy 2015 is now speaking of the "planning phase" of mingpy during this scipy 2016. https://www.youtube.com/watch?v=oE5iePv8nD8&list=PLYx7XA2nY5Gf37zYZMw6OqGFRPjB1jCy6&index=53

I may so interpolate we are at least one year away from the solution

**Comment by stonebig** [comment] 2016-08-15 15:42
ok, My understanding is that mingwpy is locked out of Python3.5 until some guy at Microsoft retires.

In the mean time, default for Cython on WinPython3.5 will be "vs" again.

**Closed** 2016-08-15 15:43 UTC
Labels: needs-discussion

**Comment by RoyiAvital** [comment] 2016-08-26 22:03
Does the current WinPython code includes `numpy` and `scipy` powered with Intel MKL?
That would be awesome!

**Comment by stonebig** [comment] 2016-08-27 07:30
It does, as all big binary packages are from cgohlke.

**Comment by RoyiAvital** [comment] 2016-08-27 08:10
Great!
Speed for everyone!

**Comment by denfromufa** [comment] 2016-12-12 07:15
There was recently introduced a gcc compiler toolchain for Python 3.5:

https://github.com/ContinuumIO/anaconda-issues/issues/561

It is called m2w64-toolchain

**Comment by stonebig** [comment] 2016-12-14 19:35
Thanks for the head-up @denfromufa. But I can't do anything of it:
- I don't have the deep pocket of Microsoft to fix their own incompatibilities.
- I don't have the big (or foolish) brains to rebuild a full un-official c-Python stack under gcc.

So the only escape route, for WinPython, is Tensorflow.

**Comment by stonebig** [comment] 2016-12-15 18:29
and edward as the replacement of pymc3

**Comment by stonebig** [comment] 2017-01-14 08:39
@denfromufa do you think "m2w64-toolchain" can be implemented in WinPython, as a mingwpy replacement for Python-3.5+ ?

**Comment by carlkl** [comment] 2017-01-14 21:40
After a hiatus (much longer than expected) I will proceed with a new version of mingwpy presumably within the next 2 weeks. The MSV CRT runtime compatibility for python-3.5, 3.6 can be only partly solved. Today file descriptors can't defined compatible with the new universal runtime UCRT due to legal reasons.

**Comment by stonebig** [comment] 2017-01-14 22:10
hi @carlkl. Happy to see you back.

**Comment by stonebig** [comment] 2017-01-23 18:55
I'm not the only one suffering in vs2015-gcc hell: https://github.com/Theano/Theano/issues/5348

**Comment by stonebig** [comment] 2017-02-03 23:27
My theano stack is dying to here some good news from mingw-64//vs2015+ front

**Comment by MichaelClerx** [comment] 2018-07-19 18:56
Was there ever any solution to this?
