### ISSUE TITLE
Spyder in WinPython-64bit-3.4.3.2 missing jedi and sphinx

### ISSUE THREAD

**Issue by yw5aj** [winpython/winpython#74] opened 2015-03-29 20:05 UTC
Hi,

First of all, thanks for the wonderful release!

A small problem here: I am using the 64-bit Python 3.4 version. When I open up spyder and check the optional dependencies, it shows that `jedi` and `sphinx` are missing. That said,

```bash
pip install sphinx
pip install jedi
```

Solved the problem though.

Shawn

**Comment by stonebig** [comment] 2015-03-29 21:41
Sphinx 1.3.1, which I included march 27th had new dependancies I didn't notice: 
- alabaster
- babel (oups! 3.4 MB)
- snowballstemmer
- sphinx-rtd-theme

Jedi was not planned for this release, as I didn't have time to evaluate it:
- do you see some advantages to include it ?
- does it remove need for other packages (like rope) ?

**Comment by yw5aj** [comment] 2015-03-29 21:49
Hi stonebig,

Spyder switched to Jedi in the 2.3.3 release, see:

https://github.com/spyder-ide/spyder/blob/master/CHANGELOG.md#version-233

So without Jedi spyder wouldn't function perfectly.

Shawn

--
Yuxiang "Shawn" Wang
Gerling Research Lab
University of Virginia
yw5aj@virginia.edu
+1 (434) 284-0836
https://sites.google.com/a/virginia.edu/yw5aj/

**Comment by stonebig** [comment] 2015-03-30 18:12
Root cause of Sphinx missing problem shoud now be fixed on my PC:
- WPPM will not show failed to install wheel packages,
- a non-installing wheel package will cause build to fail with an explicit message.

**Comment by yw5aj** [comment] 2015-03-30 20:59
Thanks @stonebig !

For the jedi - sorry that I just realized that it is listed as "Experimental", if one go to Spyder -> Help -> Optional dependencies

And that would mean currently having rope would just work. We probably wouldn't need to switch to jedi before Spyder officially replaced rope with jedi.

What do you think?

Shawn

**Comment by stonebig** [comment] 2015-03-31 17:22
Rope(s) cannot suddenly be bad because there is a new kid appearing on the block.
I wait until it's clear jedi is a safe and needed switch.

**Comment by yw5aj** [comment] 2015-03-31 18:51
Stonebig,

Yes... Totally agree. For some reasons (some posts on the spyder google
groups) I thought jedi already replaced rope, which is not true. Thanks for
looking into it!

Shawn

On Tue, Mar 31, 2015 at 1:22 PM, stonebig <notifications@github.com> wrote:

> Rope(s) cannot suddenly be bad because there is a new kid appearing on the
> block.
> I wait until it's clear jedi is a safe and needed switch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/winpython/winpython/issues/74#issuecomment-88177595>.
>



-- 
Yuxiang "Shawn" Wang
Gerling Research Lab
University of Virginia
yw5aj@virginia.edu
+1 (434) 284-0836
https://sites.google.com/a/virginia.edu/yw5aj/

**Comment by stonebig** [comment] 2015-04-01 18:57
sphinx issue solved and checked in next build

**Closed** 2015-04-01 19:45 UTC

**Comment by yw5aj** [comment] 2015-04-07 15:22
Actually - I realized that `pyreadline` seems missing as well. I guess this is due to the same reason?

**Comment by stonebig** [comment] 2015-04-07 18:32
I removed `pyreadline` because:
- it was no more supported and buggy,
- there was no wheel package either.

**Comment by yw5aj** [comment] 2015-04-07 19:36
@stonebig OIC. Thanks! I was just firing up `ipython` in windows `cmd` and it said `pyreadline` is missing. But it's true that it's losing supprot, and I think it wouldn't matter anyway because mostly in windows, we use `ipython qtconsole`.

Thanks for answering!

Shawn
